apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig

metadata:
  name: cluster-easy-way
  region: us-west-1

vpc:
  subnets:
    private:
      us-west-1a: { id: subnet-0f9bc1d45358be7b2 }
      us-west-1b: { id: subnet-0bd67466a8857d1e9 }

nodeGroups:
  - name: selfmanaged-ng-02
    instanceType: t3.large
    desiredCapacity: 2
    amiFamily: Bottlerocket
    privateNetworking: true
    iam:
       attachPolicyARNs:
          - arn:aws:iam::aws:policy/AmazonEKSWorkerNodePolicy
          - arn:aws:iam::aws:policy/AmazonEKS_CNI_Policy
          - arn:aws:iam::aws:policy/AmazonEC2ContainerRegistryReadOnly
          - arn:aws:iam::aws:policy/CloudWatchAgentServerPolicy
          - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
    ssh:
        allow: true
        publicKeyName: MyKeyPair
